baseURL = "https://tblog.sloth.yeetta.net"
disqusShortname = ""
enableGitInfo = true
enableRobotsTXT = true
hasCJKLanguage = true
languageCode = "en"
rssLimit = 10
theme = "hugo-texify3"
title = "TBlog"

[pagination]
pagerSize = 5

[taxonomies]
tags = "tags"
categories = "categories"

[params]
title="TBLog"
author = "Florus Both"
description = "A personal blog about Linux, Oracle, and other tech topics."
footnote = """
Powered by  <a class=link href=https://gohugo.io target=_blank rel=noopener>Hugo</a> | 
Theme <a class=link href=https://github.com/michaelneuper/hugo-texify3 target=_blank rel=noopener>TeXify3</a>
"""
customCSS = []
customJS = []
dateFormat = "2 January 2006"
emphasisWithDots = true
toc = true
rootFontSize = "105%"
math = true
enableDuckDuckGoSearchBox = true
numberedSubtitles = true

  [params.commentEngine]
  code = """
  <script src="https://giscus.app/client.js"
        data-repo="florusboth/TBLog"
        data-repo-id="R_kgDORJTWIg"
        data-category="Announcements"
        data-category-id="DIC_kwDORJTWIs4C167S"
        data-mapping="pathname"
        data-strict="0"
        data-reactions-enabled="1"
        data-emit-metadata="0"
        data-input-position="top"
        data-theme="gruvbox_dark"
        data-lang="en"
        data-loading="lazy"
        crossorigin="anonymous"
        async>
  </script>
  """

  [params.buymeacoffee]
  code = """
  <script async data-name="BMC-Widget" 
        data-cfasync="false" 
        src="https://cdnjs.buymeacoffee.com/1.0.0/widget.prod.min.js" 
        data-id="florusboth" 
        data-description="Support me on Buy me a coffee!" 
        data-message=""
        data-color="#FF813F" 
        data-position="Right" 
        data-x_margin="18" 
        data-y_margin="18"
        crossorigin="anonymous">
  </script>
  """
  facebook = true
  twitter = true
  email = true
  linkedin = true
  reddit = true
  whatsapp = true
  hackernews = true
  telegram = true
